FORMAT: 1A
HOST: https://oimtrust.com/api/
# Profile API
Tutorial membuat API Blueprint dengan apiary.io
# Group Profile
# Profile Collection [/profile]
### Retrieve All Profile [GET]
- Request (application/json)
- Response 200 (application/json)
    - Attributes (Profile)
### Filter Profile
- Parameters
- type : Tetap (enum[string], optional)
        - Default : `Empty`
        - Members
            - Empty
            - Tetap
            - Freelance
            - Kontrak
- Request (application/json)
- Response 200 (application/json)
    - Attributes (Profile)
# Data Structures
## Profile (object)
- id : 6c34a6af-752d-408a-b5d3-00a368e7201e (string, required)
- name : Fathur Rohim (string, required)
- email : `rohim@dot-indonesia.com` (string, required)
- phone : `081388878676` (string, required)
- type : Tetap (enum[string], required)
    - Tetap
    - Freelance
    - Kontrak
- image_url : https://www.oimtrust.com/assets/img/oim.jpg