FORMAT: 1A
HOST:  https://private-7bc5e7-examplefirman.apiary-mock.com
# Profile API
Tutorial membuat API Blueprint dengan apiary.io
# Group Profile
# Profile Collection [/profile]
### Retrieve All Profile [GET]
- Request (application/json)
- Response 200 (application/json)
    - Attributes (Profile)
### Filter Profile [GET /profile{?type}]
- Parameters
- type : Tetap (enum[string], optional)
        - Default : `Empty`
        - Members
            - Empty
            - Tetap
            - Freelance
            - Kontrak
- Request (application/json)
- Response 200 (application/json)
    - Attributes (Profile)
    
### Create Profile [POST]
- Request (application/json)
    
    - Attributes (Profile Create)
- Response 201 (application/json)
- Attributes (Profile)

# Data Structures
## Profile Create (object)
- name : Firman Dwi (string, required)
- email : `fdp080@gmail.com` (string, required)
- phone : `085870067006` (string, required)
- type : Tetap (enum[string], required)
    - Tetap
    - Freelance
    - Kontrak
## Profile (object)
- id :8c56a8af (string, required)
- Include Profile Create